export const RolesEnum = Object.freeze({
	ADMINISTRATOR: 1,
	IGROK: 2,
	TRENER: 3,
	SUDO: 7,
	GLAVNYITRENER: 8,
	VRATAR: 9,
	ZASHHITNIK: 10,
	POLUZASHHITNIK: 11,
	NAPADAIUSHHII: 12,
	RUKOVODITELDIUFK: 13,
	
});